[build]
  command = "pip install --only-binary=all fastapi uvicorn python-dotenv requests beautifulsoup4 httpx 'pydantic<2.5' jinja2 python-multipart aiofiles mangum && mkdir -p backend/static"
  functions = "netlify/functions"
  publish = "backend/static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 