[build]
  command = "python3 -m pip install -r requirements.txt && mkdir -p backend/static"
  functions = "netlify/functions"
  publish = "backend/static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 