[build]
  command = "./install_deps.sh"
  functions = "netlify/functions"
  publish = "backend/static"

[functions]
  directory = "netlify/functions"

[functions.app]
  runtime = "python3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 