[build]
  base = "."
  publish = "backend/static"
  command = "pip install -r requirements.txt && echo 'Build completed'"

[build.environment]
  PYTHON_VERSION = "3.9"
  ENVIRONMENT = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
  python_runtime = "python3.9" 