[build]
  command = "python3 -m pip install --upgrade pip && python3 -m pip install --only-binary=all --prefer-binary -r requirements-netlify.txt && mkdir -p backend/static"
  functions = "netlify/functions"
  publish = "backend/static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 